version: '3'
services:
    server:
        container_name: note-app-server
        restart: always
        build: ../server
        ports:
            - '9000:4000'
    client:
        container_name: note-app-client
        restart: always
        build: .
        ports:
            - '9001:8080'