name: Client

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cd client && npm install
    
    - name: test
      run: cd client && npm run test:unit