name: Server

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: cd server && npm install
    
    - name: test
      run: cd server && npm run test
      
    - name: lint
      run: cd server && npm run lint